use_frameworks!

platform :ios, '9.0'

target 'JKSandBoxManagerSwift_Example' do
  pod 'JKSandBoxManagerSwift', :path => '../../'

  target 'JKSandBoxManagerSwift_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 2.2.0'
    pod 'Nimble', '~> 8.0.7'
  end
end
